[package]
name = "rust-guessing-game"
version = "0.1.0"
authors = ["王俊锋 <wang1137095129@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"